CREATE TABLE llx_revenuesharing_contract (
    rowid INTEGER PRIMARY KEY AUTO_INCREMENT,
    ref VARCHAR(30) NOT NULL,
    fk_collaborator INTEGER NOT NULL,
    fk_project INTEGER,
    fk_facture INTEGER,
    label VARCHAR(255),
    amount_ht DECIMAL(10,2),
    amount_ttc DECIMAL(10,2),
    collaborator_percentage DECIMAL(5,2),
    collaborator_amount_ht DECIMAL(10,2),
    studio_amount_ht DECIMAL(10,2),
    nb_sessions INTEGER DEFAULT 0,
    cost_per_session DECIMAL(10,2) DEFAULT 0,
    total_costs DECIMAL(10,2) DEFAULT 0,
    net_collaborator_amount DECIMAL(10,2),
    status INTEGER DEFAULT 0,
    note_private TEXT,
    note_public TEXT,
    date_creation DATETIME,
    date_modification DATETIME,
    date_valid DATETIME,
    fk_user_creat INTEGER,
    fk_user_modif INTEGER,
    fk_user_valid INTEGER,
    INDEX idx_ref (ref),
    INDEX idx_fk_collaborator (fk_collaborator),
    INDEX idx_fk_project (fk_project),
    INDEX idx_fk_facture (fk_facture),
    FOREIGN KEY (fk_collaborator) REFERENCES llx_revenuesharing_collaborator(rowid),
    FOREIGN KEY (fk_project) REFERENCES llx_projet(rowid),
    FOREIGN KEY (fk_facture) REFERENCES llx_facture(rowid)
) ENGINE=InnoDB;
